version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@adonisjs/ace"
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: "@supercharge/collections"
    versions:
    - 3.1.3
